### PR TITLE
create more specific exception

### PR DESCRIPTION
**Pull request by endremborza**
this should help try/except structures work with the package better

### CODE REVIEW

**Comment by ulfaslak** [comment]
I'm not sure I see what value is added here. You're just changing the name of the exception thrown.

**Comment by endremborza** [comment]
you can do 
```
try:
    labels = model.fit_predict(...)
except NoStopsFoundException:
   pass  # here i am sure that the error was no stops found
```

instead of what you currently have to do 
```
try:
    labels = model.fit_predict(...)
except:
   pass  # here i am not quite sure what went wrong
```

**Comment by ulfaslak** [comment]
Right, I see that, but the error message describes pretty aptly what went wrong. I'm not sure giving the exception a specific name will make things much clearer.

This is not an error that occurs in any other place within the app. If we accept this change it invites us to always use custom exceptions like this, even for singleton exceptions.

**Comment by endremborza** [comment]
Using custom classes for exceptions is quite common and useful as you can catch them specifically. What you are saying is true if we only rely on the text of the exception, and would not want to catch it. If I run a program that runs many predictions, I would like it not to break if one does not find any stops, but do break when something else goes wrong. This is much easier with custom classes.

**Comment by ulfaslak** [comment]
OK now I understand your first comment much better. Yes, that is true, you could catch only `NoStopsFoundException` errors. I like that. Thanks for stating your case :)

**Pull request merged**
