### PR TITLE
Changes for Laura 

### PR DESCRIPTION
**Pull request by michielbakker**

### CODE REVIEW

**Comment by ulfaslak** [comment]
I'll review it properly and test it later today (Copenhagen time). One question though: why did you change all the print statements?

**Comment by lalessan** [comment]
To use fstrings one needs py36 at least. I think the best would be to specify that in the docs. Py35 will be deprecated next September I read.

**Comment by ulfaslak** [comment]
> To use fstrings one needs py36 at least. I think the best would be to specify that in the docs. Py35 will be deprecated next September I read.

Thanks Laura! I wasn't aware.

**Comment by michielbakker** [comment]
Hi both, changing the print statements was just a quick fix to make it work on the server as i couldn't get py35 to work. Same for the timezone inclusion, I didnt code it up in a way that works nicely with the rest of the repo (which is great btw!).

**Comment by ulfaslak** [comment]
Alright had a look. I'm reluctant to merge this pull request AS-IS, because of two things: (1) print statements can be changed package-wide, that makes sense to allow support for lower versions, but you use different syntax for string insertion and also comment them out in many place. So if I merge this, I would have to go through it and fix it, so I'd rather you format it right in this pull request. I suggest consistently using regular string insertions like `"string with %s inside it" % insert_this`. (2) The `compute_intervals_with_tz` function seems to specifically accommodate your data. Is it not possible to rewrite `compute_intervals` so that it allows any `coords` to have any number of columns? I think so, since it is guaranteed that column 0 and 1 are lat and lon.

If it is very important to your work that these updates exist in the public Infostop package, then I can merge them, however, until these things are fixed I'd rather you make these updates locally.

**Comment by ulfaslak** [comment]
I'm closing this for now. You are welcome to make the requested changes in a new PR.

**Pull request closed without merging**
